# Generated by Django 5.0.3 on 2025-09-28 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
    ]
