# Generated by Django 5.0.3 on 2025-09-28 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_auto_20250928_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('blocked', 'Blocked')], default='active', max_length=20),
        ),
    ]
